export const http =  "https://srv1005364.hstgr.cloud/api/";
export const addPlanAPI =`${http}insertplan`
export const loginApi = `${http}login`
export const getplanApi = `${http}getplan`
export const getAdsApi = `${http}getads`
export const extraplanApi = `${http}getcustom`
export const getuserscreenApi = `${http}userscreen`
export const logoutApi = `${http}logout`
export const dashboardoverviewApi = `${http}overview`
export const ScreensOverviewApi = `${http}screenstatic`
export const ScreenStatusOverviewApi = `${http}screenStatus`
export const PlanOverviewApi = `${http}planoverview`
export const EditMainPlanApi = `${http}updateplan`
export const EditCustomPlanApi = `${http}updatecustom`
export const GetIncomebyPlanApi = `${http}getAllPlansWithUserPricing`
export const GetPlansFilter = `${http}planName`
export const addAd = `${http}insertads`
export const UpdateAd =`${http}updateads`
export const DeleteAds = `${http}deleteads`
export const Getincome = `${http}incomeoverview`
export const UpdateCustom = `${http}updatecustom`
